

name: Java CI with Gradle-2

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: grant permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with gradle
      run: ./gradlew build
