

name: Java CI with Gradle-2

on:
  push:
    branches: [ "main" ]
env:
 KUBECONFIG: /home/cloudadmin/config


jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle
    - name: grant permission for gradlew
      run: chmod +x ./gradlew
    - name: Build with gradle
      run: ./gradlew build
    
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    # Check the Quality Gate status.
    - name: SonarQube Quality Gate check
      id: sonarqube-quality-gate-check
      uses: sonarsource/sonarqube-quality-gate-action@master
      # Force to fail step after specific time.
      timeout-minutes: 5
      env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       
       
    - name: Login to Nexus Registry
      uses: docker/login-action@v2
      with: 
        registry: 40.80.85.236:8083
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }} 
        
    - name:  docker build and push 
      run: |
       docker build -t 40.80.85.236:8083/javaapp:${{ github.run_number }} .
       docker push 40.80.85.236:8083/javaapp:${{ github.run_number }}
       docker rmi 40.80.85.236:8083/javaapp:${{ github.run_number }}
       
    - name: deploying manifest file on k8s
      run: |
        sed -i "s,nginx:1.0;40.80.85.236:8083/javaapp:${{ github.run_number }},g" deployment.yaml
        kubectl apply -f
        sleep 30
        kubect get pods
     
